"""Authorization coverage inventory (W2.1, Task 3).

Introspects ``core.permissions`` and classifies every *known* action into one of
four enforcement categories:

    role-gated          deterministic role gate (admin / approval-decision),
                        enforced regardless of OpenFGA configuration
    relationship-mapped checked against OpenFGA (project/workspace relations)
    generic-allowed     passes through as ``granted_stub`` (low-risk org-wide)
    unmapped-denied     not in any set → ``denied_unmapped`` (fail closed)

The first three are enumerable from the static action sets. The fourth is the
open catch-all: any action not listed elsewhere is denied, so it cannot be
enumerated — it is reported as the default-deny rule.

Run it to (re)generate ``docs/authz_coverage.md`` and print the breakdown:

    python scripts/authz_coverage.py            # writes the doc + prints summary
    python scripts/authz_coverage.py --check     # print only, do not write

The inventory drives W2.2 (coverage expansion): the generic-allowed list is the
pool of org-wide actions to audit for resource-relationship scoping.
"""
from __future__ import annotations

import sys
from datetime import date
from pathlib import Path

_API_ROOT = Path(__file__).resolve().parents[1]
if str(_API_ROOT) not in sys.path:
    sys.path.insert(0, str(_API_ROOT))

from core import permissions as p  # noqa: E402

_DOC_PATH = _API_ROOT.parents[1] / "docs" / "authz_coverage.md"


def _resource_label(action: str) -> str:
    mapped = p._resource_for(action)
    if not mapped:
        return "?"
    relation, object_type = mapped
    return f"{object_type}.{relation}"


def collect() -> dict[str, list[tuple[str, str]]]:
    """Return category → sorted list of (action, detail) rows."""
    role_gated: list[tuple[str, str]] = []
    for action in sorted(p._APPROVAL_DECISION_ACTIONS):
        role_gated.append((action, f"approver roles: {sorted(p._APPROVER_ROLES)}"))
    for action in sorted(p._ADMIN_ACTIONS):
        role_gated.append((action, f"admin roles: {sorted(p._ADMIN_ROLES)}"))

    relationship = [
        (action, _resource_label(action))
        for action in sorted(
            p._VIEW_ACTIONS
            | p._EDIT_ACTIONS
            | p._MANAGE_ACTIONS
            | p._WORKSPACE_VIEW_ACTIONS
            | p._WORKSPACE_EDIT_ACTIONS
            | p._WORKSPACE_MANAGE_ACTIONS
        )
    ]

    generic = [(action, "granted_stub") for action in sorted(p._GENERIC_ALLOWED_ACTIONS)]
    generic += [
        (f"{prefix}*", "granted_stub (prefix)")
        for prefix in sorted(p._GENERIC_ALLOWED_PREFIXES)
    ]

    return {
        "role-gated": role_gated,
        "relationship-mapped": relationship,
        "generic-allowed": generic,
    }


def render(inventory: dict[str, list[tuple[str, str]]]) -> str:
    lines: list[str] = []
    lines.append("# Authorization Coverage Inventory")
    lines.append("")
    lines.append(
        f"_Generated by `apps/api/scripts/authz_coverage.py` on {date.today().isoformat()}. "
        "Do not edit by hand — re-run the script._"
    )
    lines.append("")
    lines.append(
        "Every known action in `core.permissions.check` falls into one of four "
        "enforcement categories. This inventory enumerates the first three "
        "(static action sets); the fourth is the default-deny catch-all."
    )
    lines.append("")

    totals = {name: len(rows) for name, rows in inventory.items()}
    lines.append("## Summary")
    lines.append("")
    lines.append("| Category | Count | Enforced by |")
    lines.append("| --- | ---: | --- |")
    lines.append(
        f"| role-gated | {totals['role-gated']} | "
        "deterministic role gate, always on (no OpenFGA needed) |"
    )
    lines.append(
        f"| relationship-mapped | {totals['relationship-mapped']} | "
        "OpenFGA relationship check (fails closed when unreachable) |"
    )
    lines.append(
        f"| generic-allowed | {totals['generic-allowed']} | "
        "allowlist pass-through (`granted_stub`) — W2.2 scoping candidates |"
    )
    lines.append(
        "| unmapped-denied | (catch-all) | default deny (`denied_unmapped`) — "
        "any action not listed above |"
    )
    lines.append("")

    titles = {
        "role-gated": "Role-gated (deterministic, always on)",
        "relationship-mapped": "Relationship-mapped (OpenFGA)",
        "generic-allowed": "Generic-allowed (allowlist pass-through)",
    }
    headers = {
        "role-gated": "Required roles",
        "relationship-mapped": "FGA object.relation",
        "generic-allowed": "Decision",
    }
    for name in ("role-gated", "relationship-mapped", "generic-allowed"):
        rows = inventory[name]
        lines.append(f"## {titles[name]}")
        lines.append("")
        lines.append(f"| Action | {headers[name]} |")
        lines.append("| --- | --- |")
        for action, detail in rows:
            lines.append(f"| `{action}` | {detail} |")
        lines.append("")

    lines.append("## Unmapped (default deny)")
    lines.append("")
    lines.append(
        "Any action not present in the sets above is denied for human actors "
        "(`denied_unmapped`). Internal/system actors bypass FGA. This is the "
        "fail-closed default; adding a sensitive action without classifying it "
        "results in a deny, not a silent allow."
    )
    lines.append("")
    return "\n".join(lines)


def main(argv: list[str]) -> int:
    inventory = collect()
    doc = render(inventory)
    check_only = "--check" in argv

    totals = {name: len(rows) for name, rows in inventory.items()}
    print("Authorization coverage:")
    for name, count in totals.items():
        print(f"  {name:20s} {count}")
    print("  unmapped-denied      (catch-all default deny)")

    if not check_only:
        _DOC_PATH.parent.mkdir(parents=True, exist_ok=True)
        _DOC_PATH.write_text(doc + "\n")
        print(f"\nWrote {_DOC_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
